version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${REACT_PORT:-80}:80"
      - "${BACKEND_PORT:-3001}:3001"
    volumes:
      - ./backend/uploads:/app/backend/uploads
    environment:
      - NODE_ENV=production
      - PYTHON=/app/venv/bin/python3
      - REACT_APP_PORT=${REACT_PORT:-80}
      - REACT_APP_BACKEND_PORT=${BACKEND_PORT:-3001}
      - BACKEND_PORT=${BACKEND_PORT:-3001}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES:-5}
      - REACT_APP_BACKEND_URL=/api
